'addronce'	 'file system with a direct address used more than once'
'addronce2'	 'file system with an indirect address used more than once'
'badaddr'	 'file system with a bad direct address in an inode'
'badfmt'	 'file system without . or .. directories'
'badindir1'	 'file system with a bad indirect address in an inode'
'badindir2'	 'file system with a bad indirect address in an inode'
'badinode'	 'file system with a bad type in an inode'
'badlarge'	 'large file system with an indirect directory appearing more than once'
'badrefcnt'  'file system which has an inode that is referenced more than its reference count'
'badrefcnt2' 'file system which has an inode that is referenced more than its reference count'
'badroot'	 'file system with a root directory in bad location'
'badroot2'	 'file system with a bad root directory in good location'
'dironce'	 'file system with a directory appearing more than once'
'good'		 'good file system'
'goodlarge'	 'large good file system'
'goodlink'	 'file system with only good directory link counts'
'goodrefcnt' 'file system with only good file reference counts'
'goodrm'	 'good file system having some files removed'
'imrkfree'	 'file system with inode marked free, but referenced in a directory'
'imrkused'	 'file system with inode marked used, but not referenced in a directory'
'indirfree'	 'file system with an inuse indirect block marked free'
'mismatch'   'file system with .. pointing to the wrong directory'
'mrkfree'	 'file system with an inuse direct block marked free'
'mrkused'	 'file system with a free block marked used'